In [1]:
from numpy import *

In [4]:
arr=array([1,2,3,4,5],int)

In [5]:
print(arr)

[1 2 3 4 5]


In [11]:
arr=linspace(0,15,70)
print(arr)

[ 0.          0.2173913   0.43478261  0.65217391  0.86956522  1.08695652
  1.30434783  1.52173913  1.73913043  1.95652174  2.17391304  2.39130435
  2.60869565  2.82608696  3.04347826  3.26086957  3.47826087  3.69565217
  3.91304348  4.13043478  4.34782609  4.56521739  4.7826087   5.
  5.2173913   5.43478261  5.65217391  5.86956522  6.08695652  6.30434783
  6.52173913  6.73913043  6.95652174  7.17391304  7.39130435  7.60869565
  7.82608696  8.04347826  8.26086957  8.47826087  8.69565217  8.91304348
  9.13043478  9.34782609  9.56521739  9.7826087  10.         10.2173913
 10.43478261 10.65217391 10.86956522 11.08695652 11.30434783 11.52173913
 11.73913043 11.95652174 12.17391304 12.39130435 12.60869565 12.82608696
 13.04347826 13.26086957 13.47826087 13.69565217 13.91304348 14.13043478
 14.34782609 14.56521739 14.7826087  15.        ]


In [13]:
arr=arange(1,15,2)
print(arr)

[ 1  3  5  7  9 11 13]


In [15]:
arr=logspace(1,40,5)
print(arr)

[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]


In [17]:
arr=ones(5,float)
print(arr)

[1. 1. 1. 1. 1.]


In [18]:
arr=zeros(5,int)

In [19]:
arr

array([0, 0, 0, 0, 0])

In [20]:
arr=array([1,2,3,4])
print(arr+5)

[6 7 8 9]


In [21]:
arr1=array([6,4,3,1])
arr2=array([4,6,1,2])
print(arr1+arr2)

[10 10  4  3]


In [22]:
print(sin(arr1))

[-0.2794155  -0.7568025   0.14112001  0.84147098]


In [23]:
arr1=array([1,2,3,4])
arr2=arr1
print(id(arr1))
print(id(arr2))

2278065638064
2278065638064


In [25]:
arr2=arr1.view()
print(id(arr1))
print(id(arr2))
print(arr1)
print(arr2)

2278065638064
2278065637392
[1 2 3 4]
[1 2 3 4]


In [26]:
arr1[1]=8
print(arr1)
print(arr2)

[1 8 3 4]
[1 8 3 4]


In [27]:
arr2=arr1.copy()
arr1[1]=9
print(arr1)
print(arr2)

[1 9 3 4]
[1 8 3 4]
